# config.yml

rebelship1:
  name: "kenobi"
  x: -500
  y: -200

rebelship2:
  name: "skywalker"
  x: 100
  y: -100

rebelship3:
  name: "sato"
  x: 500
  y: 100

#connection settings  
server:
  host: 
  port: 8080
  timeout:
    server: 30
    read: 15
    write: 10
    idle: 5