# config.yml

ships:
  -  name: "BarcoUno"
     x: -500
     y: -200

  -  name: "BarcoDos"
     x: 100
     y: -100

  -  name: "BarcoTres"
     x: 500
     y: 100

#connection settings  
server:
  host: 
  port: 8080
  timeout:
    server: 30
    read: 15
    write: 10
    idle: 5